### ISSUE TITLE
[BUG] Broken Link for Service Operators

### ISSUE THREAD

**Issue by monaiuu** [tangle-network/docs#60] opened 2024-09-25 12:07 UTC
## Description

Broken 404 link when selecting from [below](https://docs.tangle.tools/operators/introduction) for '[Service Operators](https://docs.tangle.tools/operators/service-operator/service-provider)':
<img width="647" alt="Screenshot 2024-09-25 at 6 40 00 PM" src="https://github.com/user-attachments/assets/3059bf93-a41f-48c7-ad0e-b06c766409a4">

**Comment by yurixander** [comment] 2024-10-18 16:30
Can't reproduce anymore, might have been fixed already. Closing as not planned.

**Closed by yurixander** 2024-10-18 16:30 UTC
Labels: bug 🪲
